Add POST_LOAD_ASDF_SYSTEMS option to build
rigetti/quilc pull request #672
Opened 2020-08-17 17:20 UTC by colescott

Add POST_LOAD_ASDF_SYSTEMS which adds systems to be built and loaded in
the executable file. This allows for external sysytems to extend quilc
and be built into the executable without being part of the quilc system.

2020-08-19 18:50 UTC, stylewarning commented
This mostly helps in building the quilc executable. Obviously one can make new ASDF systems that _depend_ on CL-QUIL and/or QUILC.

2020-08-24 23:25 UTC, stylewarning commented on build-app.lisp
> +      (mapcar (lambda (sys)
MAP NIL

2020-08-24 23:25 UTC, stylewarning commented on build-app.lisp
> +              (uiop:split-string (or systems "quilc")
I would always load QUILC afterward; check that it's not already loaded tho.

2020-08-24 23:26 UTC, stylewarning commented on build-app.lisp
> +              (uiop:split-string (or systems "quilc")
(it doesn't hurt if it's already loaded, but double loading is a double no-bueno)

2020-08-31 17:47 UTC, colescott commented on build-app.lisp
> +              (uiop:split-string (or systems "quilc")
Well, all systems to load should be in order already. If someone passes a list without quilc in it I don't think there's a reasonable place to insert quilc. Maybe we should warn if quilc is not in the list and error if there are duplicates.

2020-08-31 17:48 UTC, stylewarning commented on build-app.lisp
> +              (uiop:split-string (or systems "quilc")
I don't get the complication. The point of this is to pre-load ASDF systems. Why not just unconditionally load quilc after all of that, so a pre-load of `""` is tolerated?

2020-08-31 17:49 UTC, stylewarning commented on build-app.lisp
> +              (uiop:split-string (or systems "quilc")
(s/pre/post/)

2020-08-31 17:50 UTC, colescott commented on build-app.lisp
> +              (uiop:split-string (or systems "quilc")
Line 46 uses the env var `ASDF_SYSTEMS_TO_LOAD` which is created in the Makefile. This is done so if for some reason in the future we want to provide systems to load _before_ quilc it will be supported.

2020-08-31 17:54 UTC, stylewarning commented on build-app.lisp
> +              (uiop:split-string (or systems "quilc")
great point, you're right, I think everything is OK now

2020-08-31 17:57 UTC, colescott commented
> can you document this new variable in the README?

Added a new section in the README with a table for build options

2020-08-31 18:08 UTC, stylewarning submitted a review, later dismissed
lgtm

2020-09-03 15:10 UTC, notmgsk requested changes
V cool addition

2020-09-03 15:10 UTC, notmgsk commented on Makefile
> +export ASDF_SYSTEMS_TO_LOAD=quilc $(POST_LOAD_ASDF_SYSTEMS)
Good for the soul if we are careful about strings here. What if `POST_LOAD_ASDF_SYSTEMS=rm -rf /`?

2020-09-03 15:10 UTC, notmgsk commented on Makefile
> +SYSTEM_LOAD_STRING=$(foreach system,$(ASDF_SYSTEMS_TO_LOAD),--eval '(ql:quickload "$(system)")')
likewise here

2020-09-03 15:10 UTC, notmgsk commented on build-app.lisp
> +      (map nil (lambda (sys)
`dolist`?

2020-09-03 15:11 UTC, notmgsk commented on Makefile
> +SYSTEM_LOAD_STRING=$(foreach system,$(ASDF_SYSTEMS_TO_LOAD),--eval '(ql:quickload "$(system)")')
Definitely here.

2020-09-03 16:42 UTC, colescott commented on build-app.lisp
> +      (map nil (lambda (sys)
Yeah. looks much better

2020-09-03 16:43 UTC, colescott commented on Makefile
> +export ASDF_SYSTEMS_TO_LOAD=quilc $(POST_LOAD_ASDF_SYSTEMS)
Should now not try to eval a string (I forgot the `make` syntax :( )

2020-09-22 16:09 UTC, stylewarning commented
@notmgsk  ping

2020-09-22 16:37 UTC, notmgsk approved these changes

2020-09-22 16:37 UTC, merged