Include readout fidelity in fidelity optimization
rigetti/quilc pull request #699
Opened 2021-01-28 17:13 UTC by notmgsk

2021-01-29 01:33 UTC, erichulburd requested changes

2021-01-29 01:33 UTC, erichulburd commented on tests/qpu-test-files/Aspen-4-2Q-B.qpu
> +{
readout-a.qpu replaces this, so this can be deleted.

2021-03-11 18:53 UTC, stylewarning commented
Can @ecpeterson look @ this?

2021-03-11 19:21 UTC, ecpeterson approved these changes

2021-03-11 19:21 UTC, ecpeterson commented on src/addresser/addresser-common.lisp
> -
daring

2021-03-11 19:21 UTC, ecpeterson commented on src/addresser/fidelity-addresser.lisp
> +        (when (typep gate 'measurement)
yikes, i didn't know this was missing. this is a good fix.

2021-04-01 14:52 UTC, notmgsk commented
Merging.

2021-04-01 14:52 UTC, merged