Load foreign libraries at run-time
rigetti/quilc pull request #702
Opened 2021-02-02 14:51 UTC by notmgsk

This allows the library-loading system to not depend solely on the
library name that was used at compile time. Example: If libffi.so.6
was used at compile time but is not present at run-time, then look for
alternatives rather than just failing.

Closes https://github.com/rigetti/pyquil/issues/1287

2021-02-02 23:35 UTC, stylewarning requested changes
My somewhat non-constructive request is to try to break this out into other toplevel functions. This is starting to resemble the entry point of the apps, which are behemoths.

2021-02-02 23:35 UTC, stylewarning commented on build-app.lisp
> -                                           #-sb-core-compression nil
oof

2021-02-02 23:35 UTC, stylewarning commented
I forgot to say, I think this is a _great_ idea, even if it's ever so slightly error prone (because the library could theoretically mismatch).

2021-03-25 18:16 UTC, stylewarning requested changes
just this one thing then it LFTM

2021-03-25 18:16 UTC, stylewarning commented on build-app.lisp
> +          (mapcar (lambda (library) (funcall (read-from-string "cffi:foreign-library-name") library))
find-symbol

2021-04-01 14:18 UTC, notmgsk commented on build-app.lisp
> +          (mapcar (lambda (library) (funcall (read-from-string "cffi:foreign-library-name") library))
`(find-symbol "LIST-FOREIGN-LIBRARIES" :cffi)` 

```
The name :CFFI does not designate any package.
```

2021-04-01 14:22 UTC, notmgsk commented on build-app.lisp
> +          (mapcar (lambda (library) (funcall (read-from-string "cffi:foreign-library-name") library))
Using `(find-symbol "LIST-FOREIGN-LIBRARIES" :CFFI)` or `(find-symbol "CFFI:LIST-FOREGIN-LIBRARIES")` evaluates to `NIL`.

2021-04-01 18:44 UTC, stylewarning commented on build-app.lisp
> +          (mapcar (lambda (library) (funcall (read-from-string "cffi:foreign-library-name") library))
```
* (ql:quickload :cffi)
To load "cffi":
  Load 1 ASDF system:
    cffi
; Loading "cffi"
.
(:CFFI)
* (find-symbol "LIST-FOREIGN-LIBRARIES" :cffi)
CFFI:LIST-FOREIGN-LIBRARIES
:EXTERNAL
```

2021-04-15 19:13 UTC, stylewarning approved these changes

2021-04-15 19:14 UTC, merged