Draft: introduce cl-quil.si package, eliminate :: refs in Quilt
rigetti/quilc pull request #707
Opened 2021-04-03 01:07 UTC by mhdavid-hrl

Eliminate use of package names with double colons (::) in Quilt, by
two methods: (1) exporting many semi-internal symbols to a new
package, cl-quil.si, and referring to them in that package; and (2) by
referring to symbols already exported (from CL-Quil) with a single
colon.

The new package, cl-quil.si (or quil.si, for short) is intended to
export system internal (SI) symbols, that is, some symbols not
generally intended to be used by the wider public, but more intended
for "friends" -- packages or facilities that are prepared to go a bit
below the surface level API.

References to most such symbols in Quilt, which previously referred to
quil::<symbol>, are changed in this commit to instead refer to
quil.si:<symbol>. (Quil.si is a nickname for cl-quil.si.)

In addition, the following symbols were already being exported from
the cl-quil package, so they were simply changed to be referred to
with single colon.

  TOK
  TOKEN-PAYLOAD
  TOKEN-TYPE
  IS-CONSTANT
  APPLICATION-ARGUMENTS
  APPLICATION-OPERATOR
  GATE-DEFINITION
  PARSED-PROGRAM-EXECUTABLE-CODE
  QUBIT-INDEX
  INSTRUCTION-FMT
  PARSE-QUIL
  GATE-DEFINITION-TO-GATE
  PERMUTATION-GATE
  PERMUTATION-GATE-PERMUTATION

2021-04-08 18:18 UTC, ecpeterson commented
If you're feeling uppity, `/app/` also has a bunch of `::`s in it and also qualifies as a friend of the cl-quil package.

2021-04-13 23:10 UTC, mhdavid-hrl commented
I replaced my earlier commit, based on @stylewarning's suggestion. Rather than doing all the stuff as a load-time form, we formalize it a bit using a newly defined macro define-exposing-package built for this purpose. 

This is ready for re-review.

2021-04-15 18:38 UTC, stylewarning requested changes

2021-04-15 18:38 UTC, stylewarning commented on src/quilt/cl-quilt.lisp
> +  (quil.si:%parse-quil string
bad indent

2021-04-15 18:38 UTC, notmgsk commented on src/package.lisp
> +(defun pre-intern-exposed-symbols (symbols package-name)
indent?

2021-04-15 18:39 UTC, stylewarning requested changes

2021-04-15 18:39 UTC, stylewarning commented on src/quilt/ast.lisp
> +  (quil.si:print-instruction-sequence (calibration-definition-body defn)
indent

2021-04-15 18:39 UTC, stylewarning commented on src/quilt/analysis/fill-delays.lisp
> +  (quil.si:list= (frame-qubits frame)
here too

2021-04-15 18:39 UTC, stylewarning commented on src/quilt/analysis/expand-calibrations.lisp
> +      (quil.si:instantiate-instruction defn
here too

2021-04-15 18:39 UTC, stylewarning commented on src/quilt/analysis/expand-calibrations.lisp
> +      (quil.si:instantiate-instruction defn
here too

2021-04-15 18:39 UTC, stylewarning commented on src/quilt/analysis/expand-calibrations.lisp
> +        (quil.si:instantiate-instruction defn
here too

2021-04-15 18:39 UTC, stylewarning commented on src/quilt/analysis/expand-calibrations.lisp
> +  (quil.si:instantiate-definition-body instr
here too

2021-04-15 18:39 UTC, stylewarning commented on src/quilt/analysis/expand-calibrations.lisp
> +  (quil.si:instantiate-definition-body instr
here too

2021-04-15 18:39 UTC, stylewarning commented on src/quilt/analysis/expand-calibrations.lisp
> +  (quil.si:instantiate-definition-body instr
h.t.

2021-04-15 18:39 UTC, stylewarning commented on src/quilt/analysis/expand-calibrations.lisp
> +         (qubits (mapcar (quil.si:flag-on-update remake
ht

2021-04-15 18:39 UTC, stylewarning commented on src/quilt/analysis/expand-calibrations.lisp
> +         (frames (mapcar (quil.si:flag-on-update remake
ht

2021-04-15 18:39 UTC, stylewarning commented on src/quilt/analysis/expand-calibrations.lisp
> +         (qubits (mapcar (quil.si:flag-on-update remake
ht

2021-04-15 18:41 UTC, stylewarning commented
todo:

- fix indentation
- remove draft status
- review/once-over by 2 ppl
- make a descriptive issue on (1) that `quil` symbols should be audited and (2) `quil.si` API should be reasoned about 
- rebase/merge

2021-04-16 00:52 UTC, mhdavid-hrl reviewed
Fixed indentation and added issue. Will now remove draft status and await review by 2 people. @notmgsk @stylewarning

2021-04-20 22:58 UTC, stylewarning approved these changes

2021-04-20 22:59 UTC, stylewarning commented
LGTM, ready to merge imho

2021-04-29 13:32 UTC, notmgsk approved these changes

2021-04-29 13:33 UTC, merged